### PR TITLE
m4 changes

### PR DESCRIPTION
**Pull request by nandub**

### CODE REVIEW

**Comment by grawity** [comment]
Commit messages need work though.

**Comment by nandub** [comment]
My bad, I went to fast and forgot to add a message.  I can amend the commit if you want?

**Comment by grawity** [comment]
eh, I think I might just rewrite the last few commits in master... 

Also, since I merged this before testing >_>, is the following expected?

<pre>
./bootstrap:3: autoreconf -fvi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
<b>aclocal: warning: couldn't open directory 'm4': No such file or directory</b>
autoreconf: configure.ac: tracing
autoreconf: configure.ac: adding subdirectory liboop to autoreconf
autoreconf: Entering directory `liboop'
<b>aclocal: warning: couldn't open directory 'm4': No such file or directory</b>
</pre>

(It does create the directory later though)

**Comment by nandub** [comment]
I noticed that as well, but when I tested it didn't affect the build, it works as expected.  Let me see if I can figure out how to remove the warning.

**Comment by nandub** [comment]
It looks like it previously it use to error out but they change the message to a warning.  I can add `aclocal --install` before the `autoreconf -fvi` to work around the warning.  Let me send another PR not sure if updating this PR will do anything as you already MERGED it.

**Comment by nandub** [comment]
Let's revert this PR.  It adds more verbosity to the build when adding the `aclocal --install`

**Pull request merged**
